name: Tests CI

on: []

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: cd PHASE_1/API_SourceCode/App && npm install
      - run: cd PHASE_1/API_SourceCode/App && npm run test:ci
        env: 
          FIRESTORE_TYPE: ${{ secrets.FIRESTORE_TYPE }}
          FIRESTORE_PROJECT_ID: ${{ secrets.FIRESTORE_PROJECT_ID }}
          FIRESTORE_PRIVATE_KEY_ID: ${{ secrets.FIRESTORE_PRIVATE_KEY_ID }}
          FIRESTORE_PRIVATE_KEY: ${{ secrets.FIRESTORE_PRIVATE_KEY }}
          FIRESTORE_CLIENT_EMAIL: ${{ secrets.FIRESTORE_CLIENT_EMAIL }}
          FIRESTORE_CLIENT_ID: ${{ secrets.FIRESTORE_CLIENT_ID }}
          FIRESTORE_AUTH_URI: ${{ secrets.FIRESTORE_AUTH_URI }}
          FIRESTORE_TOKEN_URI: ${{ secrets.FIRESTORE_TOKEN_URI }}
          FIRESTORE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.FIRESTORE_AUTH_PROVIDER_X509_CERT_URL }}
          FIRESTORE_CLIENT_X509_CERT_URL: ${{ secrets.FIRESTORE_CLIENT_X509_CERT_URL }}

      - name: Tests ✅
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: Tests 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
